apps:
  - name: dist-db-project
    interpreter: babel-node
    script: src/index.js
    args: []
    no-daemon: false
    log_date_format: YYYY-MM-DD HH:mm:ss
    watch: false
    min_uptime: 10000
    max_restarts: 1
    env:
      NODE_ENV: development
      PORT: 3300
      GOOGLE_APPLICATION_CREDENTIALS: /Users/songpon/dist-db-project/dist-db-project-5017775c524e.json
      GOOGLE_STORAGE_BUCKET_ID: youpin-widget-staging
      POSTMARK_API_TOKEN: 8b0cd0e0-bde7-41ba-bcbf-678a2363402c
      POSTMARK_FROM: rapee@boonmeelab.com
