apps:
  - name: dist-db-project
    interpreter: babel-node
    script: src/index.js
    args: []
    no-daemon: false
    log_date_format: YYYY-MM-DD HH:mm:ss
    watch: false
    min_uptime: 10000
    max_restarts: 1
    env:
      NODE_ENV: development
      PORT: 3300
      GOOGLE_APPLICATION_CREDENTIALS: /Users/songpon/dist-db-project/dist-db-project-5017775c524e.json
      GOOGLE_STORAGE_BUCKET_ID: dist-db-project
      MONGODB: mongodb+srv://Petchill:pe111333@youpin-0iyxk.gcp.mongodb.net/dist-db-project
